---
title: "Practica2_Inferencia"
author: "Miguel Ángel Gragera García"
date: "9/2/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cargar datos

```{r cars}
#install.packages("readr")
#install.packages("dplyr")
#install.packages("ggplot2")
#install.packages("GGally")
library (dplyr)
ruta_Excel_CalidadAire <- "CalidadAire14_19_zonaProv.csv"
data_CalidadAire <- read.csv(ruta_Excel_CalidadAire, header=TRUE, sep=';', 
                             dec = ',')
CalidadAire <- select(data_CalidadAire, Year, CodProv, Population,
          PM10.population.weighted.average..ug.m3., 
          PM2.5.population.weighted.average..ug.m3., 
          NO2.population.weighted.average..ug.m3., 
          O3.SOMO35.population.weighted.average..ug.days.m3.)

names (CalidadAire) = c("Year", "CodProv", "Population", "Factor_PM10", 
                        "Factor_PM2.5", "Factor_NO2", "Factor_O3")

CalidadAire_Final <- CalidadAire %>% 
  group_by(CodProv, Year) %>% 
  summarise_all(sum)

ruta_Excel_datosCP <- "Datos_CP_14_19_prov.csv"
data_datosCP <- read.csv(ruta_Excel_datosCP, header=TRUE, sep=";")
names (data_datosCP) = c("Year", "CodProv", "CIE10", "Provincia", 
                         "SumaTotal", "value_f", "value_m")
data_final <- merge(data_datosCP, CalidadAire_Final, by = c("Year", "CodProv"))
data_final$Prevalencia = round( (data_final$SumaTotal * 100000) / data_final$Population , 2 )
head(data_final)

```

## BoxPlot 

You can also embed plots, for example:

```{r pressure, echo=FALSE}
boxplot(data_final$SumaTotal)
```
```{r}
boxplot(data_final$Prevalencia)
```
## Correlación
```{r}
Data_Correlacion_SumaTotal <- select(data_final, Factor_PM10, Factor_PM2.5, Factor_NO2, Factor_O3, Prevalencia)
round(cor(Data_Correlacion_SumaTotal),4)
library(ggplot2)
library(GGally)
ggpairs(Data_Correlacion_SumaTotal, lower = list(continuos="smooth"), diag = list(continuos="barDiag"), axislabels="none")
```

## Selección variables menor pValues para la regresión

```{r}
modelo <- lm(Prevalencia~Factor_PM10 + Factor_PM2.5 + Factor_NO2 + Factor_O3, data = Data_Correlacion_SumaTotal)
summary(modelo)
```
## Regresión lineal múltiple

Se seleccionan las variables factor03, factorPM2.5, FactorPm10

```{r}
library(caTools)
library(caret)

set.seed(123)
split = sample.split(Data_Correlacion_SumaTotal$Prevalencia, SplitRatio = 0.8)
training_set = subset(Data_Correlacion_SumaTotal, split == TRUE)
testing_set = subset(Data_Correlacion_SumaTotal, split == FALSE)

regression =  lm(Prevalencia~Factor_PM10 + Factor_PM2.5  + Factor_O3, data = training_set)

y_pred = predict(regression, newdata = testing_set)

RMSE(y_pred, testing_set$Prevalencia)
R2(y_pred, testing_set$Prevalencia)
y_pred
testing_set$Prevalencia
y_compared = data.frame(y_pred,testing_set$Prevalencia )

plot( testing_set$Prevalencia  - y_pred)
```
## Refresión SVR

```{r}
library(e1071)
regression = svm(formula = Prevalencia~Factor_PM10 + Factor_PM2.5  + Factor_O3,
                 data = training_set, 
                 type = "eps-regression", 
                 kernel = "radial")
y_pred = predict(regression, newdata =testing_set )
RMSE(y_pred, testing_set$Prevalencia)
R2(y_pred, testing_set$Prevalencia)
y_pred
testing_set$Prevalencia
y_compared = data.frame(y_pred,testing_set$Prevalencia )

plot( testing_set$Prevalencia  - y_pred)
```


## Regresión RF

```{r}
library(randomForest)
set.seed(1234)
regression = randomForest(x = training_set[, 1:4],
                          y = training_set$Prevalencia,
                          ntree = 100)
y_pred = predict(regression, newdata =testing_set )
RMSE(y_pred, testing_set$Prevalencia)
R2(y_pred, testing_set$Prevalencia)
y_pred
testing_set$Prevalencia
y_compared = data.frame(y_pred,testing_set$Prevalencia )

plot( testing_set$Prevalencia  - y_pred)
```

##  Intervalo de confianza bilateral para la diferencia de medias
```{r}
n <- length(data_final$Prevalencia)    # El tamaño válido de la muestra
media <- mean(data_final$Prevalencia) # la media 
desv <- sd(data_final$Prevalencia)  # La desviación estándar. Datos históricos
nivelconfianza = 0.95

#error.est <- desv/sqrt(n) # Calculamos el error estándar
#margen.error <- 1.644854 * error.est # nivel de confianza de 90% 


#lim.inf <- media - margen.error # Límite inferior del intervalo
#lim.inf

#lim.sup <- media + margen.error # Límite superior del intervalo
#lim.sup

#install.packages("BSDA")
library(BSDA)

zsum.test(mean.x=media,sigma.x=desv, n.x=n,conf.level=nivelconfianza)


par(mfrow=c(1, 2))
require(car)  # Debe instalar antes el paquete car
qqPlot(data_final$Prevalencia, pch=19,
       main='QQplot para la prevalencia',
       xlab='Cuantiles teóricos',
       ylab='Cuantiles muestrales')

hist(data_final$Prevalencia , freq=TRUE,
     main='Histograma para la prevalencia',
     xlab='Prevalencia',
     ylab='Frecuencia')
```

